hypoxia.lib: atco.upd
         UPD atco.for
         FOR1 update.out,atco,prn;
         PAS2

hypoxia.lib: blco2.upd
         UPD blco2.for
         FOR1 update.out,blco2,prn;
         PAS2

hypoxia.lib: blo2.upd
         UPD blo2.for
         FOR1 update.out,blo2,prn;
         PAS2

hypoxia.lib: calck.upd
         UPD calck.for
         FOR1 update.out,calck,prn;
         PAS2

hypoxia.lib: chart.upd
         UPD chart.for
         FOR1 update.out,chart,prn;
         PAS2

hypoxia.lib: chart2.upd
         UPD chart2.for
         FOR1 update.out,chart2,prn;
         PAS2

hypoxia.lib: chart3.upd
         UPD chart3.for
         FOR1 update.out,chart3,prn;
         PAS2

hypoxia.lib: chrtok.upd
         UPD chrtok.for
         FOR1 update.out,chrtok,prn;
         PAS2

hypoxia.lib: credit.upd
         UPD credit.for
         FOR1 update.out,credit,prn;
         PAS2

hypoxia.lib: csh.upd
         UPD csh.for
         FOR1 update.out,csh,prn;
         PAS2

hypoxia.lib: def.upd
         UPD def.for
         FOR1 update.out,def,prn;
         PAS2

hypoxia.lib: diff.upd
         UPD diff.for
         FOR1 update.out,diff,prn;
         PAS2

hypoxia.lib: farhi.upd
         UPD farhi.for
         FOR1 update.out,farhi,prn;
         PAS2

hypoxia.lib: gilbert.upd
         UPD gilbert.for
         FOR1 update.out,gilbert,prn;
         PAS2

hypoxia.lib: gtchrt.upd
         UPD gtchrt.for
         FOR1 update.out,gtchrt,prn;
         PAS2

hypoxia.lib: hfile.upd
         UPD hfile.for
         FOR1 update.out,hfile,prn;
         PAS2

hypoxia.lib: hlist.upd
         UPD hlist.for
         FOR1 update.out,hlist,prn;
         PAS2

hypoxia.lib: hypbd.upd
         UPD hypbd.for
         FOR1 update.out,hypbd,prn;
         PAS2

hypoxia.lib: hypdel.upd
         UPD hypdel.for
         FOR1 update.out,hypdel,prn;
         PAS2

hypoxia.lib: hyplot.upd
         UPD hyplot.for
         FOR1 update.out,hyplot,prn;
         PAS2

hypoxia.lib: hyplst.upd
         UPD hyplst.for
         FOR1 update.out,hyplst,prn;
         PAS2

hypoxia.lib: hypxmn.upd
         UPD hypxmn.for
         FOR1 update.out,hypxmn,prn;
         PAS2

hypoxia.lib: mit.upd
         UPD mit.for
         FOR1 update.out,mit,prn;
         PAS2

hypoxia.lib: o2diss.upd
         UPD o2diss.for
         FOR1 update.out,o2diss,prn;
         PAS2

hypoxia.lib: read.upd
#        UPD read.for
#        FOR1 update.out,read,prn;
#        PAS2

hypoxia.lib: report.upd
         UPD report.for
         FOR1 update.out,report,prn;
         PAS2

hypoxia.lib: root.upd
         UPD root.for
         FOR1 update.out,root,prn;
         PAS2

hypoxia.lib: setngo.upd
         UPD setngo.for
         FOR1 update.out,setngo,prn;
         PAS2

hypoxia.lib: stamp.upd
         UPD stamp.for
         FOR1 update.out,stamp,prn;
         PAS2

hypoxia.lib: write.upd
         UPD write.for
         FOR1 update.out,write,prn;
         PAS2

hypoxia.lib: write2.upd
         UPD write2.for
         FOR1 update.out,write2,prn;
         PAS2

hypoxia.obj: hypoxia.upd
             UPD hypoxia.for
             FOR1 update.out,hypoxia,prn;
             PAS2

